import { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Spider-Man 2',
    description: 'Jogue como Peter Parker e Miles Morales em uma nova aventura épica no universo Spider-Man.',
    price: 299.90,
    originalPrice: 349.90,
    platform: 'PS5',
    category: 'Action',
    images: ['https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg'],
    features: ['Modo História', 'Mundo Aberto', 'Cooperativo Local'],
    rating: 4.8,
    reviewCount: 1250,
    inStock: true,
    stockQuantity: 50,
    releaseDate: new Date('2023-10-20'),
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2023-10-01')
  },
  {
    id: '2',
    title: 'Forza Horizon 5',
    description: 'Explore o mundo aberto mais diverso da série Forza Horizon no México vibrante.',
    price: 199.90,
    platform: 'Xbox Series X/S',
    category: 'Racing',
    images: ['https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg'],
    features: ['Mundo Aberto', 'Multiplayer Online', '4K Ultra HD'],
    rating: 4.7,
    reviewCount: 890,
    inStock: true,
    stockQuantity: 75,
    releaseDate: new Date('2021-11-09'),
    createdAt: new Date('2021-10-15'),
    updatedAt: new Date('2021-10-15')
  },
  {
    id: '3',
    title: 'God of War Ragnarök',
    description: 'Kratos e Atreus embarcam em uma jornada mítica em busca de respostas e aliados.',
    price: 249.90,
    originalPrice: 299.90,
    platform: 'PS4',
    category: 'Action',
    images: ['https://images.pexels.com/photos/3165335/pexels-photo-3165335.jpeg'],
    features: ['Modo História', 'Gráficos Aprimorados', 'Combate Épico'],
    rating: 4.9,
    reviewCount: 2100,
    inStock: true,
    stockQuantity: 30,
    releaseDate: new Date('2022-11-09'),
    createdAt: new Date('2022-10-20'),
    updatedAt: new Date('2022-10-20')
  },
  {
    id: '4',
    title: 'Halo Infinite',
    description: 'Master Chief retorna na aventura Halo mais ambiciosa de todos os tempos.',
    price: 179.90,
    platform: 'Xbox One',
    category: 'Shooter',
    images: ['https://images.pexels.com/photos/3165335/pexels-photo-3165335.jpeg'],
    features: ['Campanha Solo', 'Multiplayer Free-to-Play', 'Mundo Semi-Aberto'],
    rating: 4.5,
    reviewCount: 1500,
    inStock: false,
    stockQuantity: 0,
    releaseDate: new Date('2021-12-08'),
    createdAt: new Date('2021-11-20'),
    updatedAt: new Date('2021-11-20')
  },
  {
    id: '5',
    title: 'The Last of Us Part I',
    description: 'Reviva a jornada de Joel e Ellie com gráficos completamente reconstruídos.',
    price: 229.90,
    platform: 'PS5',
    category: 'Adventure',
    images: ['https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg'],
    features: ['Modo História', 'Gráficos Remasterizados', 'Acessibilidade Aprimorada'],
    rating: 4.6,
    reviewCount: 980,
    inStock: true,
    stockQuantity: 40,
    releaseDate: new Date('2022-09-02'),
    createdAt: new Date('2022-08-15'),
    updatedAt: new Date('2022-08-15')
  },
  {
    id: '6',
    title: 'FIFA 24',
    description: 'A experiência de futebol mais autêntica com HyperMotion V e novas tecnologias.',
    price: 259.90,
    platform: 'PS5',
    category: 'Sports',
    images: ['https://images.pexels.com/photos/274422/pexels-photo-274422.jpeg'],
    features: ['Ultimate Team', 'Carreira', 'Multiplayer Online'],
    rating: 4.3,
    reviewCount: 750,
    inStock: true,
    stockQuantity: 60,
    releaseDate: new Date('2023-09-29'),
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2023-09-15')
  },
  {
    id: '7',
    title: 'Starfield',
    description: 'Explore a galáxia na nova franquia RPG espacial da Bethesda Game Studios.',
    price: 299.90,
    platform: 'Xbox Series X/S',
    category: 'RPG',
    images: ['https://images.pexels.com/photos/586063/pexels-photo-586063.jpeg'],
    features: ['Mundo Aberto Espacial', 'Exploração Planetária', 'Personalização Profunda'],
    rating: 4.4,
    reviewCount: 1100,
    inStock: true,
    stockQuantity: 25,
    releaseDate: new Date('2023-09-06'),
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2023-08-20')
  },
  {
    id: '8',
    title: 'Tekken 8',
    description: 'A luta continua com gráficos de nova geração e Heat System revolucionário.',
    price: 279.90,
    platform: 'PS5',
    category: 'Fighting',
    images: ['https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg'],
    features: ['Modo Arcade', 'Multiplayer Online', 'Sistema Heat'],
    rating: 4.7,
    reviewCount: 650,
    inStock: true,
    stockQuantity: 35,
    releaseDate: new Date('2024-01-26'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10')
  }
];

// Function to seed the database with mock data
export const seedMockData = async () => {
  // This would be used to populate Firebase with initial data
  // Implementation would depend on your Firebase setup
  console.log('Mock data ready for seeding:', mockProducts);
};